FROM quay.io/nushell/nu:devel
LABEL Maintainer vsochat@stanford.edu
RUN apt-get update && \
    apt-get install -y python3 python3-pip && \
    pip3 install nushell pyinstaller
WORKDIR /code
COPY nu_plugin_hello /code/nu_plugin_hello
RUN pyinstaller --onefile nu_plugin_hello && \
    cp dist/nu_plugin_hello /usr/local/bin/nu_plugin_hello && \
    pip3 uninstall -y nushell
ENTRYPOINT ["/bin/bash"]
