################################################################################
# Functions
################################################################################

# Defaults

defaults: &defaults
  working_directory: /tmp/src


# Environment

sourceenv: &sourceenv
    name: Source environment variables from the BASH_ENV
    command: source $BASH_ENV 

install: &install
  name: install dependencies
  command: |
     sudo pip3 install --upgrade pylint pytest


run_linter: &run_linter
  name: run linter
  command: |
     cd /tmp/src
     pylint nushell --ignore=nushell/tests


test_nushell: &test_nushell
  name: Test Nushell Plugin Library in Python
  command: |
        which python
        python --version
        cd /tmp/src
        sudo python setup.py install
        pytest nushell/tests/test*.py


################################################################################
# Jobs
################################################################################


version: 2
jobs:

  test-python-3:
    <<: *defaults
    docker:
      - image: circleci/python:3.6.4
    steps:
      - checkout
      - setup_remote_docker     
      - run: *install
      - run: *run_linter
      - run: *test_nushell


################################################################################
# Workflows
################################################################################


workflows:
  version: 2
  build_deploy:
    jobs:
      - test-python-3:
          filters:
            branches:
              ignore: master
